version: "3.8"
services:
  gsd-frontend:
    image: edchelstephens/gsd:dd8a807237324dafae20dd51e7eaa7cc932df0d2
    command: python app.py
    deploy:
      replicas: 10
    ports:
      - target: 8080
        published: 5000
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /code
  redis:
    image: "redis:alpine"
    networks:
      counter-net:

networks:
  counter-net:

volumes:
  counter-vol:
